version: '3.8'

services:
  redis:
    image: redis:bookworm
    container_name: redis
    ports:
      - "6379:6379"

  server:
    container_name: server
    build:
      context: .
      dockerfile: dockerfile-server
    volumes:
      - ./server:/app/
    ports:
      - "8008:8008"
    environment:
      - PORT=8008      
    entrypoint: /start-reload.sh